import { Component } from '@angular/core';
import { newCard } from './individual-new';

@Component({
  selector: 'app-home-news-section',
  templateUrl: './home-news-section.component.html',
  styleUrls: ['./home-news-section.component.css']
})
export class HomeNewsSectionComponent {
  cards = [
    new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
      new newCard('https://www.capital21.cdmx.gob.mx/noticias/wp-content/uploads/2020/10/unam-min.jpg', 
      '10 de Mayo, 2025', 'Periodo de Inscripción Semestre 2026-1', 
      'Consulta las fechas y el procedimiento para reinscribirte al próximo semestre.'),
  ]

}
